
LOOT_STRUCTURE_WRECK = ["hgun_ACPC2_F","hgun_ACPC2_snds_F","hgun_P07_F","hgun_P07_snds_F","hgun_Pistol_heavy_01_F","hgun_Pistol_heavy_01_snds_F","hgun_Pistol_heavy_01_MRD_F","hgun_Pistol_heavy_02_F","hgun_Pistol_heavy_02_Yorris_F","hgun_Rook40_F","hgun_Rook40_snds_F","hgun_Pistol_Signal_F"];
LOOT_STRUCTURE_VILLAGE = ["ItemWatch", "hgun_Pistol_heavy_01_F", "11Rnd_45ACP_Mag"];
LOOT_STRUCTURE_TRANSPORT = ["hgun_ACPC2_F","hgun_ACPC2_snds_F","hgun_P07_F","hgun_P07_snds_F","hgun_Pistol_heavy_01_F","hgun_Pistol_heavy_01_snds_F","hgun_Pistol_heavy_01_MRD_F","hgun_Pistol_heavy_02_F","hgun_Pistol_heavy_02_Yorris_F","hgun_Rook40_F","hgun_Rook40_snds_F","hgun_Pistol_Signal_F"];
LOOT_STRUCTURE_TOWN = ["hgun_ACPC2_F","hgun_ACPC2_snds_F","hgun_P07_F","hgun_P07_snds_F","hgun_Pistol_heavy_01_F","hgun_Pistol_heavy_01_snds_F","hgun_Pistol_heavy_01_MRD_F","hgun_Pistol_heavy_02_F","hgun_Pistol_heavy_02_Yorris_F","hgun_Rook40_F","hgun_Rook40_snds_F","hgun_Pistol_Signal_F", "SMG_01_F", "SMG_02_F", "30Rnd_9x21_Mag", "arifle_Katiba_ACO_F", "30Rnd_65x39_caseless_green_mag_Tracer", "30Rnd_65x39_caseless_green"];
LOOT_STRUCTURE_MILITARY = ["arifle_Katiba_ACO_pointer_F", "arifle_Katiba_ACO_pointer_snds_F", "30Rnd_65x39_caseless_green", "30Rnd_65x39_caseless_green_mag_Tracer", "arifle_Katiba_ARCO_F"];
LOOT_STRUCTURE_INDUSTRIAL = ["hgun_ACPC2_F","hgun_ACPC2_snds_F","hgun_P07_F","hgun_P07_snds_F","hgun_Pistol_heavy_01_F","hgun_Pistol_heavy_01_snds_F","hgun_Pistol_heavy_01_MRD_F","hgun_Pistol_heavy_02_F","hgun_Pistol_heavy_02_Yorris_F","hgun_Rook40_F","hgun_Rook40_snds_F","hgun_Pistol_Signal_F"];
LOOT_STRUCTURE_INFRASTRUCTURE = ["hgun_ACPC2_F","hgun_ACPC2_snds_F","hgun_P07_F","hgun_P07_snds_F","hgun_Pistol_heavy_01_F","hgun_Pistol_heavy_01_snds_F","hgun_Pistol_heavy_01_MRD_F","hgun_Pistol_heavy_02_F","hgun_Pistol_heavy_02_Yorris_F","hgun_Rook40_F","hgun_Rook40_snds_F","hgun_Pistol_Signal_F"];
LOOT_STRUCTURE_CULTURAL = ["hgun_ACPC2_F","hgun_ACPC2_snds_F","hgun_P07_F","hgun_P07_snds_F","hgun_Pistol_heavy_01_F","hgun_Pistol_heavy_01_snds_F","hgun_Pistol_heavy_01_MRD_F","hgun_Pistol_heavy_02_F","hgun_Pistol_heavy_02_Yorris_F","hgun_Rook40_F","hgun_Rook40_snds_F","hgun_Pistol_Signal_F", "11Rnd_45ACP_Mag", "6Rnd_45ACP_Cylinder", "16Rnd_9x21_Mag", "arifle_Katiba_ACO_pointer_F", "arifle_Katiba_ACO_pointer_snds_F", "30Rnd_65x39_caseless_green", "30Rnd_65x39_caseless_green_mag_Tracer", "arifle_Katiba_ARCO_F"];
LOOT_STRUCTURE_COMMERICIAL = ["hgun_ACPC2_F","hgun_ACPC2_snds_F","hgun_P07_F","hgun_P07_snds_F","hgun_Pistol_heavy_01_F","hgun_Pistol_heavy_01_snds_F","hgun_Pistol_heavy_01_MRD_F","hgun_Pistol_heavy_02_F","hgun_Pistol_heavy_02_Yorris_F","hgun_Rook40_F","hgun_Rook40_snds_F","hgun_Pistol_Signal_F", "11Rnd_45ACP_Mag", "11Rnd_45ACP_Mag", "arifle_Katiba_ACO_pointer_F", "arifle_Katiba_ACO_pointer_snds_F", "30Rnd_65x39_caseless_green", "30Rnd_65x39_caseless_green_mag_Tracer", "arifle_Katiba_ARCO_F"];
