
LOOT_STRUCTURE_WRECK = ["ItemWatch"];
LOOT_STRUCTURE_VILLAGE = ["ItemWatch"];
LOOT_STRUCTURE_TRANSPORT = ["ItemWatch"];
LOOT_STRUCTURE_TOWN = ["ItemWatch"];
LOOT_STRUCTURE_MILITARY = ["ItemWatch"];
LOOT_STRUCTURE_INDUSTRIAL = ["ItemWatch"];
LOOT_STRUCTURE_INFRASTRUCTURE = ["ItemWatch"];
LOOT_STRUCTURE_CULTURAL = ["ItemWatch"];
LOOT_STRUCTURE_COMMERICIAL = ["ItemWatch"];
